### ISSUE TITLE
Update README with lenses

### ISSUE THREAD

**Issue by staltz** [staltz/cycle-onionify#15]

**Comment by jvanbruegge** [comment]
Am I right that this would allow for a global state part in addition to the normal onionify behavior?

**Comment by staltz** [comment]
Hi @jvanbruegge I don't understand your question, can you be more specific?

**Comment by jvanbruegge** [comment]
Do the lenses allow me to specify that a part of my state is global, so every component can access it? And do I have to pass the same lense over and over again to reexport the global state?

**Comment by staltz** [comment]
Yes and no. Lenses allow you to specify that **any** part (or even any computation from any part of the state) of your state **looks like it is global** once given to the child component. On the other hand, if you have a deep hierarchy Grandparent => Parent => Child, you will need another lens between Parent and Child, because there is no magical transfer of "this is global state" down the hierarchy. And it won't be the same lens over and over again. Of course nothing stops you from making lens factories to make this transfer easier.

**Comment by staltz** [comment]
I think this is mostly done now with abaco's PR.
