### ISSUE TITLE
Vocabulary: action vs intent 

### ISSUE THREAD

**Issue by cluelessjoe** [staltz/cycle-onionify#23]
Hi

Reading the README and others examples I was surprised at the use of "Action" when describing the intents.

Indeed, it introduces a new term whereas we speak of MVI, aka Model View Intent, where the term action is completely out of the picture.

Furthermore, what's called actions here are some intents: it's not because the user "asks for it" that it'll happen. Some business logic might contradict the user's will here. For example the chosen login might be already given to someone else.

So, why not call these actions intents?

The model would then get a stream of Intent, which is way more in sync with MVI, and all would be simpler.

I suspect I'm missing something but I don't see what so...

++

**Comment by staltz** [comment]
Hi :)
I'd recommend checking our official docs on MVI, in particular this part: https://cycle.js.org/model-view-intent.html#model-view-intent-summarized

> intent() function
> Purpose: interpret DOM events as **user’s intended actions**
> Input: DOM source
> Output: **Action Streams**
