### ISSUE TITLE
[Question] How to share data?

### ISSUE THREAD

**Issue by Andarist** [staltz/cycle-onionify#3]
As the state becomes fractal I wonder how sharing data across application not in a parent-child component hierarchy is possible. Its easy to imagine that this is super common scenario. I guess its possible to communicate the closest common ancestor so it could store this shared state, but what about refactoring? From what I've seen you need to go 'manually' through each layer so if that's the solution then you need to refactor the code so you will reference i.e. to the 4th and not 3rd ancestor. Maybe I'm missing something here, not a Cycle expert anyway, but im rly interested in the topic.

**Comment by staltz** [comment]
Can you give an example of "not in a parent-child component hierarchy"?

**Comment by Andarist** [comment]
Hm, for example a template of what to render in another part of the app. Configuring template being done somewhere deep in the branch A of the state, while using that template to render some dynamic view is being made somewhere deep in the branch B of the state.

**Comment by blicksky** [comment]
If I understand what @Andarist is asking correctly, I've been trying to figure this out as well. Let's try combining your basic and advanced examples to illustrate this. What if you had a counter display at the"top" of the app as well as a list of to-do items, but each todo item had the increment and decrement buttons in them, and any of them could change the value of the counter. How would you pass around the state of the counter?

**Comment by staltz** [comment]
Here's some code for that scenario @blicksky: https://github.com/staltz/cycle-onionify/tree/master/examples/mixed

In short, here's the idea:

- Top-level state object is just `{counter: {...}, list: {...}}` https://github.com/staltz/cycle-onionify/blob/master/examples/mixed/src/TodoApp.ts#L9-L12
- The Counter component is exactly the same as what you can see from `examples/counter`. Just saying that this code was not modified https://github.com/staltz/cycle-onionify/blob/master/examples/mixed/src/Counter.ts 
- The Item component in the list exports a `counterReducer$` as a sink. This is not isolated. It just operates on a state object that looks like state object for the Counter. https://github.com/staltz/cycle-onionify/blob/master/examples/mixed/src/Item.ts#L42-L53
- The List component (parent of Item) exports also `counterReducer$` which is all Item counterReducer$ merged together https://github.com/staltz/cycle-onionify/blob/master/examples/mixed/src/List.ts#L40-L48
- The App component takes the counterReducer$ from the List component and isolates that sink to the "counter" scope, so these reducers will operate on the field `counter` in the top-level state object `{counter: {...}, list: {...}}` https://github.com/staltz/cycle-onionify/blob/master/examples/mixed/src/TodoApp.ts#L85

**Comment by blicksky** [comment]
Awesome, thanks so much for your thorough answer and updating the examples!
