### ISSUE TITLE
Version 4.0.0-rc.8 should should adapt collection$

### ISSUE THREAD

**Issue by ntilwalli** [staltz/cycle-onionify#41]
The `collection$` returned from `asCollection` should be adapted.
```
return adapt(collection$);
```
https://github.com/staltz/cycle-onionify/blob/collection/src/index.ts#L233

**Comment by staltz** [comment]
@ntilwalli How are you going to use `pickMerge` and `pickCombine`? the stream returned from asCollection is rather useless in itself. I would actually wait until (there's a PR) we have the API where `asCollection` returns a CollectionSource which has the operators `pickMerge` and `pickCombine` as methods, so we could have adapt() in those methods instead.

**Comment by ntilwalli** [comment]
Yeah, while playing with the example yesterday I ran into the issue of `pickMerge`/`pickCombine` not yet being RxJS-compatible issue and then got diverted.  Thanks! I look forward to that PR!
