### ISSUE TITLE
"Reducer" term is not correct

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle-onionify#57]
"Reducer" is, by definition, a binary function of the form `(a, b) => a` (left fold) or `(a, b) => b` (right fold). In this project "reducer" term is used for `state => state2` like transformations, so I believe it's misleading.

I suppose the name was chosen as "familiar" after Redux, but I think that being technically precise is more important. The real reducer is this guy:

```js
(state, fn) => fn(state)
```

The `mapper` term would be closer, btw.

**Comment by staltz** [comment]
Hi @ivan-kleshnin. I understand the background you're presenting here, but I think that being familiar is more important than being technically precise, specially in an ecosystem like JavaScript that doesn't have such precise technical definitions, unlike Haskell.
