### ISSUE TITLE
emitting `xs.never` with pickCombine might be wrong

### ISSUE THREAD

**Issue by jvanbruegge** [staltz/cycle-onionify#64]
I thought about it, and basicly this will block the combine from emitting at all, so it is basicly a silent failure. For `merge` `never` is the right thing to do, but the other half of my PR might be better to roll back

**Comment by staltz** [comment]
@jvanbruegge Oh, that's true. The zero in a merge is never. The zero in a combine is empty.

**Comment by jvanbruegge** [comment]
What does combine even emit anything if nothing was emitted prior to complete?

**Comment by staltz** [comment]
@jvanbruegge I think empty() is not the true zero element for combine() but pickCombine is slightly different than combine regarding the completions and starts of each inner stream, because pickCombine allows a dynamic number of inner streams

**Comment by staltz** [comment]
So I took a careful look at pickCombine. Both pickMerge and pickCombine ignore complete, so it's not a matter of choosing between xs.never() or xs.empty() (because except for completions, they are the same).

pickCombine emits an array equivalent to the number of children involved, so we can't omit the array entry for that child component, there must be *something* in that array entry. I think we should use then `xs.of(undefined)` so that the array entry for that child will be undefined. Either that or null.

What do you think?

**Comment by jvanbruegge** [comment]
I would actually let it throw an error. Either that or some way to get access to the array of children, so you can filter yourself. Or a second `pickCombine` that filters the children

**Comment by staltz** [comment]
The filtering could be done easily on the array using xstream `filter`, for instance right before this `map`:

https://github.com/staltz/cycle-onionify/blob/9b2baf50e189c959ab4f988f348816a133174fad/examples/advanced/src/TodoApp.ts#L71

How would you suggest the error to be thrown? Calling `out._e(new Error)` if `sinks[sel]` is undefined here?: 

https://github.com/staltz/cycle-onionify/blob/9b2baf50e189c959ab4f988f348816a133174fad/src/pickCombine.ts#L124

**Comment by jvanbruegge** [comment]
I would not pass the error downstream. Just throw it right there to inform the developer he screwed up. Collection only contains items of the same type, and while merge is normal to automaticly combine children, e.g. via a combinator (like `pickMergeSinks`). So when you manually use `pickCombine` you have screwed up

**Comment by staltz** [comment]
So `pickMerge('HTTP')` when an item doesn't have HTTP sink would not error, and `pickCombine('HTTP')` would error? I wonder if throwing for pickMerge would also be better than merging xs.never().

**Comment by jvanbruegge** [comment]
My main reason is, with `merge` you dont care, just merge all for me. In thr combinator `pickMergeSinks` you have to tell which drivers you want to merge. Normally, for convenience reasons, I simply pass the `driverNames` which is `Object.keys(drivers)`. This way, I dont have to update my code when I add a new driver/wrapper.

**Comment by staltz** [comment]
Yeah, combine has requirements for the member streams, while merge has no requirements. I'll throw an error, and release a new version.

**Comment by staltz** [comment]
And I'll change those tests you added, so that we don't expect errors for pickMerge, but expect errors for pickCombine.

**Comment by jvanbruegge** [comment]
Yeah, thank you
