### ISSUE TITLE
Action stream is probably a better definition than `reducer` stream.

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [staltz/cycle-onionify#65]
Distinction:
A reducer is a function `reducer :: Action -> State -> State`. 
An action is a function `action :: State -> State`.
What you describe as returning to `onion` is a stream of actions not a stream of reducers.

A stream of actions also has a more intuitive meaning.

**Comment by dev-matan-tsuberi** [comment]
Common sense:
- A reducer is a function you use in `[1,2,3].reduce(reducer, initialState)`
- An action is a function that takes one state to another (state transition).

Other:
- `redux` calls functions of type `fn :: State -> Action -> State` reducers.

**Comment by staltz** [comment]
Well, "common sense" actually varies from group to another. :) You can think of onionify as *defining* the term reducer as being `State -> State`, not *borrowing* from other projects like Redux.
