### ISSUE TITLE
Define Omit<T, K> properly?

### ISSUE THREAD

**Issue by ryota-ka** [staltz/cycle-onionify#70]
Currently `Omit<T, K>` type is defined as a mere alias of `any`, which results in the situation where the core `onionify` function is quite loosely typed.
https://github.com/staltz/cycle-onionify/blob/8b6344a749fb5b0ad7c0c8f1dcf2db4e5e1cda03/src/onionify.ts#L27

As you know, however, we already have conditional types in TypeScript 2.8+, so we can define the type properly with `Pick` and `Exclude`.

It also has some drawbacks:

- The change requires the dependency of TypeScript 2.8+
  - currently depending on 2.5.x
- It will possibly be a  breaking change toward codebases with improperly typed onionified components
  - thus it'll require a major version bump

**Comment by staltz** [comment]
Forgot to mention that this package is now superseded by https://cycle.js.org/api/state.html which is the same source code (basically). I need to update the readme
